import BaseForm, { FORM_ERROR } from "./Base_Form/Form";
import LabeledRadioInput from "./Base_Form/LabeledRadioInput";
import LabeledSelectInput from "./Base_Form/LabeledSelectInput";
import LabeledTextField from "./Base_Form/LabeledTextField";
import LabeledTextArea from "./Base_Form/LabeledTextArea";
import TextAreaWithFormContext from "./Base_Form/TextAreaWithFormContext";
import {
  ActivityFeed,
  NotifGeneric,
  NotifWrapper,
  NotifInvite,
  Notifs,
  NotifBell,
  NotifMeeting,
  NotifPopupParent,
  NotifQuestionaire,
} from "./Notifications";
import ProfileSection from "./Sidebar/ProfileSection";
import Sidebar from "./Sidebar/Sidebar";
import {
  BtnDefault,
  BtnJoinCall,
  // BtnSetupCall,
  BtnTeamMenu,
  BtnTeamMenuSection,
  Switch,
} from "./Button";
import { CalCell, CalCellActivity, CalParent } from "./Calendar";
import { ContactForm, ContactSection, Emotions, UserEmotion } from "./Contact";
import {
  Chore,
  ChoreForTMSection,
  ChoreForUserSection,
  Goal,
  GoalWrapper,
  TaskForTM,
  TaskForUser,
  FrequencyForUser,
  FrequencyForTM,
  FreqTaskCell,
  EditAUserGoal,
  Frequency1OForUser,
  Frequency1OForTM,
  ChartBar,
  TaskLegend,
  TaskTimeline,
  TaskHistoryWrapper,
} from "./GoalSystem";
import {
  Card,
  CardContent,
  CardForEmailInvite,
  InviteAMember,
  InviteScroll,
  InviteWrapper,
} from "./Invitation";
import {
  ConsentForm,
  DateSelector,
  SelectorMeetWith,
  SelectorDuration,
  FrequencySelector,
  Input,
  LabeledSelectField,
  Select,
  TextArea,
  TimeSelector,
} from "./Form/index";
import {
  MeetCalBody,
  MeetCalHeader,
  MeetCalParent,
  MeetCalDateCell,
  MeetCalRequestForm,
  MeetCalBodyRowLabels,
  MeetCalCallBookmark,
  MeetCalTimeNow,
} from "./Meeting";
import {
  CommentForm,
  TitleWithDetails,
  CommentsWrapper,
  EmojiResponse,
  EmojiBar,
  MsgBubble,
  MsgBubbleForComment,
  MsgForm,
  TeamMsgsParent,
  TeamMsgsLog,
  TeamMsgsTitlebar,
  MsgsIcon,
} from "./Messaging";
import {
  CheckBoxGeneric,
  ConfirmationBox,
  Dashboard,
  Delete,
  Footer,
  Loader,
  MStatementHelp,
  Navbar,
  NavbarInCall,
  Overlay,
  QAWidget,
  ThePactContent,
  Tooltip,
  UserDetailsInTeamWrapper,
  UserMissionStatement,
  UserInfoInTeam,
  UserIntro,
  YoutubeVideo,
} from "./Common";
import {
  AddGoalOrChoreForm,
  CallTeamMsgsAndGoalsWrapper,
  CallTeamMsgsSection,
  CallTMGoalsChoresList,
  CallUserGoalsChoresList,
  ChangeLog,
  Portal,
  QASection,
  TeamViewMobile,
  TMSideInTeam,
  TwitterFeed,
  UserSideInTeam,
} from "./Unique";
import { OnboardingParent } from "./Onboarding";
import {
  GoalFormAddNew,
  ChoreForm,
  ChoresListingForm,
  DueCalendarField,
  PanelEditor,
  GoalsForm,
  GoalsFormBtns,
  GoalForm,
  GoalFormGuide,
  GoalFormSwitch,
  GoalTaskForm,
  GoalChoreFormDeleteBox,
  // GoalTaskFormForOne,
  GoalTaskEditorRgtSide,
  GoalTaskFreqSelectorWidget,
} from "./Editor";
import {
  TeamMenu,
  TeamMenuWrapper,
  TeamExpiryNotice,
  Team3DayGracePeriod,
  TeamEndConfirmationBox,
} from "./TeamMenu";
import {
  DisplayReview,
  ReviewButton,
  ReviewMetaSection,
  ReviewForm,
  ReviewReactionForm,
  ReviewContent,
  WeekHistory,
  WeekLinks,
  WeeklyReviewMain,
} from "./WeeklyReview";

export {
  // BtnSetupCall,
  // GoalTaskFormForOne,
  // Questionaire,
  ActivityFeed,
  AddGoalOrChoreForm,
  BaseForm,
  BtnDefault,
  BtnJoinCall,
  BtnTeamMenu,
  BtnTeamMenuSection,
  CalCell,
  CalCellActivity,
  CallTeamMsgsAndGoalsWrapper,
  CallTeamMsgsSection,
  CallTMGoalsChoresList,
  CallUserGoalsChoresList,
  CalParent,
  Card,
  CardContent,
  CardForEmailInvite,
  ChangeLog,
  ChartBar,
  CheckBoxGeneric,
  Chore,
  ChoreForm,
  ChoreForTMSection,
  ChoreForUserSection,
  ChoresListingForm,
  CommentForm,
  CommentsWrapper,
  ConfirmationBox,
  ConsentForm,
  ContactForm,
  ContactSection,
  Dashboard,
  DateSelector,
  Delete,
  DisplayReview,
  DueCalendarField,
  EditAUserGoal,
  EmojiBar,
  EmojiResponse,
  Emotions,
  Footer,
  FORM_ERROR,
  FreqTaskCell,
  Frequency1OForTM,
  Frequency1OForUser,
  FrequencyForTM,
  FrequencyForUser,
  FrequencySelector,
  Goal,
  GoalChoreFormDeleteBox,
  GoalForm,
  GoalFormAddNew,
  GoalFormGuide,
  GoalFormSwitch,
  GoalsForm,
  GoalsFormBtns,
  GoalTaskEditorRgtSide,
  GoalTaskForm,
  GoalTaskFreqSelectorWidget,
  GoalWrapper,
  Input,
  InviteAMember,
  InviteScroll,
  InviteWrapper,
  LabeledRadioInput,
  LabeledSelectField,
  LabeledSelectInput,
  LabeledTextArea,
  LabeledTextField,
  Loader,
  MeetCalBody,
  MeetCalBodyRowLabels,
  MeetCalCallBookmark,
  MeetCalDateCell,
  MeetCalHeader,
  MeetCalParent,
  MeetCalRequestForm,
  MeetCalTimeNow,
  MsgBubble,
  MsgBubbleForComment,
  MsgForm,
  MsgsIcon,
  MStatementHelp,
  Navbar,
  NavbarInCall,
  NotifBell,
  NotifGeneric,
  NotifInvite,
  NotifMeeting,
  NotifPopupParent,
  NotifQuestionaire,
  Notifs,
  NotifWrapper,
  OnboardingParent,
  Overlay,
  PanelEditor,
  Portal,
  ProfileSection,
  QASection,
  QAWidget,
  ReviewButton,
  ReviewContent,
  ReviewForm,
  ReviewMetaSection,
  ReviewReactionForm,
  Select,
  SelectorDuration,
  SelectorMeetWith,
  Sidebar, // can be disabled?
  Switch,
  TaskForTM,
  TaskForUser,
  TaskHistoryWrapper,
  TaskLegend,
  TaskTimeline,
  TeamEndConfirmationBox,
  TeamExpiryNotice,
  TeamMenu,
  TeamMenuWrapper,
  TeamMsgsLog,
  TeamMsgsParent,
  TeamMsgsTitlebar,
  TeamViewMobile,
  Team3DayGracePeriod,
  TextArea,
  TextAreaWithFormContext,
  ThePactContent,
  TimeSelector,
  TitleWithDetails,
  TMSideInTeam,
  Tooltip,
  TwitterFeed,
  UserDetailsInTeamWrapper,
  UserEmotion,
  UserInfoInTeam,
  UserIntro,
  UserMissionStatement,
  UserSideInTeam,
  WeekHistory,
  WeekLinks,
  WeeklyReviewMain,
  YoutubeVideo,
};
